#Changed the file type to .yml  for new technologies
#Use yamllint.com to validate the code yaml
server:
  port: 80
cors: #Global CORS
  originPatterns: http://localhost:3000,http://localhost:8080,https://afos.com.br
file:
  upload-dir: C:/springboot-rest-dir
security:
  jwt:
    token:
      secret-key: 53cr37
      expire-lenght: 3600000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_rest_springboot?useTimezone=true&serverTimezone=UTC
    username: root #username for aws application
    password: admin123
  jpa:
    hibernate:
      ddl-auto: none #for more: https://stackoverflow.com/questions/438146/what-are-the-possible-values-of-the-hibernate-hbm2ddl-auto-configuration-and-wha
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
springdoc:
  pathsToMatch: 
    - /**/v1 #/api/**/v1/**
    - /auth/**
    - /file/**
  swagger-ui:
    use-root-path: true
