#CORS global form
server:
  port: 8080
cors:
  originPatterns: http://localhost:3000,http://localhost:8080,https://andrefilipeos.com.br
file: #for upload files
  upload-dir: C:/springboot-rest-dir
#JWT Security
security:
  jwt:
    token:
      secret-key: 53cr37
      expire-length: 3600000 #milli-seconds
#Changed the file type to .yml  for new technologies
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_springboot_db?useTimezone=true&serverTimeZone=UTC
    username: root
    password: admin123
  jpa:
    hibernate:
      ddl-auto: none  #only read and write data
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: false #true only for debugging mode
  servlet: #for upload files
    multipart: 
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
          
springdoc:
  pathsToMatch: #for swagger api
    -  /api/**/v1/**
    -  /auth/**
  swagger-ui:
    use-root-path: true